[package]
name = "pixel-gaia"
version = "0.1.0"
edition = "2021"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[features]
inspector = ["bevy-inspector-egui"]

[dependencies]
anyhow = "1"
arrayvec = "0.7"
bevy = "0.8"
bevy_asset_loader = "0.13"
bevy_common_assets = { version = "0.3", features = ["ron"] }
bevy_egui = "0.16"
bevy-inspector-egui = { version = "0.13", optional = true }
bincode = "1"
clap = { version = "4", features = ["derive"] }
fnv = "1"
log = "0.4"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }

tile-geom = { git = "https://github.com/garkimasera/tile-geom.git" }

[profile.dev]
opt-level = 1
