lang = "English"

camera_move_speed = 48.0
autosave_enabled = true
autosave_cycle_duration = 1000
autosave_max_files = 5
manual_max_files = 5
screen_refresh_rate = "medium"
show_fps = false

[ui]
scale_factor = 1.0
font_scale = 1.2
messages_in_list = 32
min_sidebar_width = 200
