lang = "English"

camera_move_speed = 48.0
autosave_enabled = true
autosave_cycle_duration = 1000
autosave_max_files = 5
manual_max_files = 5
report_lifespan = 2000
screen_refresh_rate = "medium"
show_fps = false
sound_effect_volume = 100
bgm_volume = 100
slow_speed_sim_duration_ms = 250
medium_speed_sim_duration_ms = 100

[ui]
scale_factor = 1.0
font_scale = 1.2
reports_in_list = 10
min_sidebar_width = 200
