[animal]
allosaurus = "Allosaurus"
ant = "Ant"
crab = "Crab"
crocodile = "Crocodile"
dunkleosteus = "Dunkleosteus"
elephant = "Elephant"
fox = "Fox"
hornet = "Hornet"
ichthyostega = "Ichthyostega"
jellyfish = "Jellyfish"
lizard = "Lizard"
octopus = "Octopus"
raccoon-dog = "Raccoon Dog"
rat = "Rat"
raven = "Raven"
shark = "Shark"
starfish = "Starfish"
stenonychosaurus = "Stenonychosaurus"
tribrachidium = "Tribrachidium"

[civ]
allosaurus = "Allosaurus Civilization"
ant = "Ant Civilization"
crab = "Crab Civilization"
crocodile = "Crocodile Civilization"
dunkleosteus = "Fishman Civilization"
elephant = "Elephant Civilization"
fox = "Fox Civilization"
hornet = "Hornet Civilization"
ichthyostega = "Ichthyostega Civilization"
jellyfish = "Jellyfish Civilization"
lizard = "Lizardman Civilization"
octopus = "Octopus Civilization"
raccoon-dog = "Raccoon Dog Civilization"
rat = "Rat Civilization"
raven = "Raven Civilization"
shark = "Shark Civilization"
starfish = "Starfish Civilization"
stenonychosaurus = "Dinosauroid Civilization"
tribrachidium = "Tribrachidium Civilization"
