# UI
air-temperature = "Temperature"
animal = "Animal"
argon = "Argon"
atmosphere = "Atmosphere"
atmosphere-pressure = "Atmospheric Pressure"
average-air-temperature = "Average Temperature"
average-rainfall = "Average Rainfall"
average-sea-temperature = "Average Sea Temperature"
back = "Back"
biomass = "Biomass"
biome = "Biome"
biomes = "Biomes"
build = "Build"
building-limit-reached = "Building limit reached"
buried-carbon = "Buried Carbon"
cancel = "Cancel"
carbon = "Carbon"
carbon-dioxide = "Carbon Dioxide"
cities = "Cities"
city = "City"
civilization = "Civilization"
civilization-ages = "Civilization Ages"
civilize = "Civilize"
civilize-cost = "Civilize Cost"
civilized = "Already Civilized"
civilizing-in-progress = "Civilizing in Progress"
close = "Close"
coordinates = "Coordinates"
cost = "Cost"
cycles = "Cycles"
date-saved = "Date"
delete = "Delete"
demolition = "Demolition"
density = "Density"
details = "Details"
difference-in-elevation = "Difference in Elevation"
enabled = "Enabled"
energy = "Energy"
energy-consumption = "Energy Consumption"
energy-sources = "Energy Sources"
exit = "Exit"
fertility = "Fertility"
focus = "Focus"
gene-points = "Gene Points"
habitability = "Habitability"
habitat = "Habitat"
height = "Height"
help = "Help"
high = "High"
history = "History"
latitude = "Latitude"
livable-temperature = "Livable Temperature"
large = "Large"
layers = "Layers"
load = "Load"
longitude = "Longitude"
low = "Low"
main-menu = "Main Menu"
map = "Map"
material = "Material"
medium = "Medium"
menu = "Menu"
messages = "Messages"
new = "New"
new-planet = "New Planet"
next = "Next"
next-tutorial = "Next Tutorial"
nitrogen = "Nitrogen"
no-civilization = "No Civilization"
not-enough = "Not Enough"
none = "None"
ok = "OK"
orbit = "Orbit"
oxygen = "Oxygen"
planet = "Planet"
planet-name = "Planet Name"
population = "Population"
power = "Power"
preferences = "Preferences"
produce = "Produce"
project = "Project"
radius = "Radius"
rainfall = "Rainfall"
random-name = "Random Name"
resume = "Resume"
save = "Save"
save-as = "Save As"
search-new-planet = "Search New Planet"
size = "Size"
small = "Small"
solar-constant = "Solar Constant"
spawn = "Spawn"
speed-fast = "Fast speed"
speed-medium = "Medium speed"
speed-paused = "Pause"
speed-slow = "Slow speed"
star-system = "Star system"
start = "Start"
statistics = "Statistics"
structures = "Structures"
tile-event = "Tile Event"
tile-events = "Tile Events"
tutorial = "Tutorial"
upkeep = "Upkeep"
water = "Water"

# Biomes
land = "Land"
sea = "Sea"
rock = "Rock"
ocean = "Ocean"
sea-ice = "Sea Ice"
desert = "Desert"
ice-sheet = "Ice Sheet"
tundra = "Tundra"
grassland = "Grassland"
boreal-forest = "Boreal Forest"
temperate-forest = "Temperate Forest"
tropical-rainforest = "Tropical Rainforest"

# Structures
oxygen-generator = "Oxygen Generator"
rainmaker = "Rainmaker"
fertilization-plant = "Soil Fertilization Plant"
heater = "Heater"
carbon-capturer = "Carbon Capturer"
gift-tower = "Gift Tower"
settlement = "Settlement"

# Space Buildings
fusion-reactor = "Fusion Reactor"
asteroid-mining-station = "Asteroid Mining Station"
dyson-swarm-unit = "Dyson Swarm Unit"
orbital-mirror = "Orbital Mirror"
solar-shield = "Solar Shield"
ice-importer = "Ice Importer"
nitrogen-importer = "Nitrogen Importer"
carbon-importer = "Carbon Importer"
ion-irradiator = "Ion Irradiator"

# Tile Events
aerosol-injection = "Aerosol Injection"
black-dust = "Black Dust"
fire = "Fire"
plague = "Plague"
vehicle = "Vehicle"
war = "War"

# Civilization Ages
[age]
stone = "Stone"
bronze = "Bronze"
iron = "Iron"
industrial = "Industrial"
atomic = "Atomic"
early-space = "Early Space"

# Energy sources
[energy_source]
biomass = "Biomass"
wind-solar = "Wind & Solar"
hydro-geothermal = "Hydro & Geothermal"
fossil-fuel = "Fossil Fuel"
nuclear = "Nuclear"
gift = "Gift"

# Preferences
[preference]
autosave-enabled = "Enable Autosave"
screen-refresh-rate = "Screen Refresh Rate"
show-fps = "Show FPS"

# Messages
[msg]
animal-insufficient-population = "Insufficient Population"
lack-of-gene-points = "Lack of Gene Points"
loading-failed = "Loading failed"
loading-failed-desc-decode-error = "Loading failed. The save data was created with an incompatible version or is corrupted."
loading-failed-desc-not-found = "Loading failed. Cannot find saved data."
delete-save-data = "Delete the following save data?"
save-limit = "Due to storage limitations, you cannot create multiple save data files when playing on the web."
save-limit-strong = "Do you want to delete the following save data and start a new game? This action cannot be undone."
web-limit-warning = "You are running Gaia Maker in a web browser. When running in a web browser, the number of save data and performance are limited. If you want to play without limitations, please use the download version."
