# UI
air-temperature = "Temperature"
animal = "Animal"
argon = "Argon"
atmosphere = "Atmosphere"
atmosphere-pressure = "Atmospheric Pressure"
average-air-temperature = "Average Temperature"
average-rainfall = "Average Rainfall"
average-sea-temperature = "Average Sea Temperature"
back = "Back"
biomass = "Biomass"
biome = "Biome"
build = "Build"
buried-carbon = "Buried Carbon"
cancel = "Cancel"
carbon = "Carbon"
carbon-dioxide = "Carbon Dioxide"
cities = "Cities"
city = "City"
civilization = "Civilization"
civilize = "Civilize"
civilized = "Already Civilized"
civilizing-in-progress = "Civilizing in Progress"
close = "Close"
coordinates = "Coordinates"
cost = "Cost"
cycles = "Cycles"
date-saved = "Date"
delete = "Delete"
demolition = "Demolition"
density = "Density"
details = "Details"
difference-in-elevation = "Difference in Elevation"
enabled = "Enabled"
energy = "Energy"
energy-consumption = "Energy Consumption"
exit = "Exit"
fertility = "Fertility"
gene-points = "Gene Points"
habitability = "Habitability"
habitat = "Habitat"
height = "Height"
help = "Help"
high = "High"
history = "History"
latitude = "Latitude"
livable-temperature = "Livable Temperature"
large = "Large"
layers = "Layers"
load = "Load"
longitude = "Longitude"
low = "Low"
main-menu = "Main Menu"
map = "Map"
material = "Material"
medium = "Medium"
menu = "Menu"
messages = "Messages"
new = "New"
new-planet = "New Planet"
next = "Next"
next-tutorial = "Next Tutorial"
nitrogen = "Nitrogen"
no-civilization = "No Civilization"
none = "None"
ok = "OK"
orbit = "Orbit"
oxygen = "Oxygen"
planet = "Planet"
planet-name = "Planet Name"
population = "Population"
power = "Power"
preferences = "Preferences"
produce = "Produce"
project = "Project"
radius = "Radius"
rainfall = "Rainfall"
random-name = "Random Name"
save = "Save"
save-to-slot = "Save to slot {$slot}"
save-to-slot-disabled = "Save to slot        "
search-new-planet = "Search New Planet"
size = "Size"
small = "Small"
solar-constant = "Solar Constant"
spawn = "Spawn"
speed-fast = "Fast speed"
speed-normal = "Normal speed"
speed-paused = "Pause"
star-system = "Star system"
start = "Start"
statistics = "Statistics"
structures = "Structures"
tile-event = "Tile Event"
tutorial = "Tutorial"
upkeep = "Upkeep"
water = "Water"

# Biomes
land = "Land"
sea = "Sea"
rock = "Rock"
ocean = "Ocean"
sea-ice = "Sea Ice"
desert = "Desert"
ice-field = "Ice Field"
tundra = "Tundra"
grassland = "Grassland"
boreal-forest = "Boreal Forest"
temperate-forest = "Temperate Forest"
tropical-rainforest = "Tropical Rainforest"

# Structures
oxygen-generator = "Oxygen Generator"
rainmaker = "Rainmaker"
fertilization-plant = "Fertilization Plant"
heater = "Heater"
carbon-capturer = "Carbon Capturer"
gift-tower = "Gift Tower"
settlement = "Settlement"

# Space Buildings
fusion-reactor = "Fusion Reactor"
asteroid-mining-station = "Asteroid Mining Station"
dyson-swarm-unit = "Dyson Swarm Unit"
orbital-mirror = "Orbital Mirror"
solar-shield = "Solar Shield"
ice-importer = "Ice Importer"
nitrogen-importer = "Nitrogen Importer"
carbon-importer = "Carbon Importer"
ion-irradiator = "Ion Irradiator"

# Tile Events
aerosol-injection = "Aerosol Injection"
black-dust = "Black Dust"
fire = "Fire"
plague = "Plague"

# Civilization Ages
[age]
stone = "Stone"
bronze = "Bronze"
iron = "Iron"
industrial = "Industrial"
atomic = "Atomic"
early-space = "Early Space"

# Energy sources
[energy_source]
biomass = "Biomass"
wind-solar = "Wind & Solar"
hydro-geothermal = "Hydro & Geothermal"
fossil-fuel = "Fossil Fuel"
nuclear = "Nuclear"
gift = "Gift"

# Preferences
[preference]
autosave-enabled = "Enable Autosave"
max-simulation-speed = "Max simulation speed"

# Messages
[msg]
warn-high-temp = "Too high temperature\nAn effective way to lower the temperature is to operate the orbital mirrors, an orbital structure, to block sunlight from reaching the ground surface."
warn-low-oxygen = "Too low oxygen\nThere is not enough oxygen in the air. It is necessary to install an oxygen generator or to produce oxygen through photosynthesis by plants."
warn-low-temp = "Too low temperature\nAn effective way to raise the temperature is to operate the orbital mirrors, to increase the amount of sunlight reaching the surface."
loading-failed = "Loading failed"
loading-failed-desc-decode-error = "Loading failed. The save data was created with an incompatible version or is corrupted."
loading-failed-desc-not-found = "Loading failed. Cannot find saved data."
delete-save-data = "Delete the following save data?"
save-limit = "Due to storage limitations, you cannot create multiple save data files when playing on the web."
save-limit-strong = "Do you want to delete the following save data and start a new game? This action cannot be undone."

# Events
[event]
start = "Arrival at a new planet\nYou have arrived on a barren, undeveloped planet. Depending on the conditions of the planet, you can build various facilities to transform it into an environment suitable for life.\nYou need Energy to maintain the facilities and Material to build them. Energy can be produced by building fusion reactors in orbit and Material can be produced by building asteroid mining stations in the star system.\nPlease refer to the help for further information as needed."
