[report]
warn-high-temp = "The temperature is too high. An effective way to lower the temperature is to operate the Orbital Mirror to block stellar light from reaching the ground surface."
warn-low-carbon-dioxide = "There is not enough carbon dioxide in the atmosphere. This can inhibit plant growth and may even cause a cooling effect. It is necessary to either start up Carbon Importers or burn buried carbon."
warn-low-oxygen = "There is not enough oxygen in the air. Build Oxygen Generators or Carbon Capturers."
warn-low-temp = "The temperature is too low. An effective way to raise the temperature is to operate the Orbital Mirror to increase the amount of stellar light reaching the surface."
animal-born = "{$animal} has been born."
achive-civilization = "{$animal} has achived civiliation."
civilized = "The process of civilizing {$animal} has been completed."
civ-advance = "{$civ} advanced into the {$age} Age."
civ-extinct = "{$civ} has become extinct."
civ-decadence = "The decadence of {$civ} began."
inter-species-war = "{$civ_a} and {$civ_b} started a war."
inter-species-war-ceased = "The war between {$civ_a} and {$civ_b} ended."
nuclear-war = "A nuclear war began."
