[animal]
allosaurus = "アロサウルス"
ant = "アリ"
crab = "カニ"
crocodile = "ワニ"
elephant = "ゾウ"
dunkleosteus = "ダンクルオステウス"
fox = "キツネ"
hornet = "ハチ"
ichthyostega = "イクチオステガ"
jellyfish = "クラゲ"
lizard = "トカゲ"
octopus = "タコ"
raccoon-dog = "タヌキ"
rat = "ネズミ"
raven = "カラス"
shark = "サメ"
starfish = "ヒトデ"
stenonychosaurus = "ステノニコサウルス"
tribrachidium = "トリブラキディウム"

[civ]
allosaurus = "アロサウルス文明"
ant = "アリ文明"
crab = "カニ文明"
crocodile = "ワニ文明"
dunkleosteus = "魚人文明"
elephant = "ゾウ文明"
fox = "キツネ文明"
hornet = "ハチ文明"
ichthyostega = "イクチオステガ文明"
jellyfish = "クラゲ文明"
lizard = "トカゲ文明"
octopus = "タコ文明"
raccoon-dog = "タヌキ文明"
rat = "ネズミ文明"
raven = "カラス文明"
shark = "サメ文明"
starfish = "ヒトデ文明"
stenonychosaurus = "恐竜人文明"
tribrachidium = "トリブラキディウム文明"
