[animal]
ant = "アリ"
crocodile = "ワニ"
elephant = "ゾウ"
fox = "キツネ"
hornet = "ハチ"
jellyfish = "クラゲ"
octopus = "タコ"
raccoon-dog = "タヌキ"
raven = "カラス"
shark = "サメ"
stenonychosaurus = "ステノニコサウルス"
tribrachidium = "トリブラキディウム"

[civ]
ant = "アリ文明"
crocodile = "ワニ文明"
elephant = "ゾウ文明"
fox = "キツネ文明"
hornet = "ハチ文明"
jellyfish = "クラゲ文明"
octopus = "タコ文明"
raccoon-dog = "タヌキ文明"
raven = "カラス文明"
shark = "サメ文明"
stenonychosaurus = "恐竜人文明"
tribrachidium = "トリブラキディウム文明"
