# UI
air-temperature = "気温"
animal = "動物"
argon = "アルゴン"
atmosphere = "大気"
atmosphere-pressure = "気圧"
average-air-temperature = "平均気温"
average-rainfall = "平均降水量"
average-sea-temperature = "平均海水温"
biomass = "生物量"
biome = "バイオーム"
build = "建設"
cancel = "キャンセル"
carbon = "炭素"
carbon-dioxide = "二酸化炭素"
civilization = "文明"
civilize = "文明化"
close = "閉じる"
coordinates = "座標"
cost = "コスト"
demolition = "撤去"
density = "密度"
details = "詳細"
difference-in-elevation = "高低差"
difficulty = "難易度"
difficulty-easy = "簡単"
difficulty-hard = "難しい"
difficulty-normal = "普通"
difficulty-very-easy = "とても簡単"
difficulty-very-hard = "とても難しい"
enabled = "有効"
energy = "エネルギー"
exit = "終了"
fertility = "肥沃度"
gene-point = "遺伝子ポイント"
habitat = "生息環境"
height = "高さ"
history = "歴史"
latitude = "緯度"
large = "大型"
layers = "レイヤー"
livable-temperature = "生存可能温度"
load = "ロード"
longitude = "経度"
main-menu = "メインメニュー"
map = "地図"
material = "素材"
medium = "中型"
menu = "メニュー"
messages = "メッセージ"
new = "新規"
nitrogen = "窒素"
none = "なし"
orbit = "軌道"
oxygen = "酸素"
planet = "惑星"
produce = "産出"
project = "プロジェクト"
radius = "半径"
rainfall = "降水量"
save = "セーブ"
save-to-slot = "スロット {$slot} にセーブ"
save-to-slot-disabled = "スロットにセーブ    "
search-new-planet = "新しい惑星"
size = "サイズ"
small = "小型"
solar-constant = "太陽定数"
spawn = "配置"
speed-fast = "高速"
speed-normal = "通常速度"
speed-paused = "停止"
star-system = "星系"
start = "開始"
statistics = "統計"
structures = "構造物"
upkeep = "維持"
water = "水"
help = "ヘルプ"

# Biomes
land = "陸"
sea = "海"
rock = "岩石"
ocean = "海"
sea-ice = "海氷"
desert = "砂漠"
ice-field = "氷原"
tundra = "ツンドラ"
grassland = "草原"
boreal-forest = "針葉樹林"
temperate-forest = "温帯樹林"
tropical-rainforest = "熱帯雨林"

# Structures
oxygen-generator = "酸素発生機"
rainmaker = "降雨装置"
fertilization-plant = "肥沃化工場"
heater = "ヒーター"
carbon-capturer = "炭素還元機"
settlement = "居住地"

# Civilization Ages
stone-age = "石器時代"
bronze-age = "青銅器時代"
iron-age = "鉄器時代"
industrial-age = "工業化時代"
atomic-age = "原子力時代"
early-space-age = "初期宇宙時代"

# Space Buildings
fusion-reactor = "核融合炉"
asteroid-mining-station = "小惑星採掘ステーション"
dyson-swarm-unit = "ダイソンスウォームユニット"
orbital-mirror = "軌道ミラー"
nitrogen-importer = "窒素輸送機"
carbon-importer = "炭素輸送機"
ion-irradiator = "イオン放射機"

# Messages
[msg]
warn-high-temp = "高すぎる気温\n気温が高すぎます。気温を下げるには、軌道上建造物である軌道ミラーを稼働させ、地表に届く太陽光を遮蔽することが効果的です。"
warn-low-oxygen = "酸素が少ない\n大気中に十分な酸素がありません。酸素発生機を設置するか、植物の光合成により酸素を生みだす必要があります。"
warn-low-temp = "低すぎる気温\n気温が低すぎます。気温を上げるには、軌道上建造物である軌道ミラーを稼働させ、地表に届く太陽光を増やすことが効果的です。"
loading-failed = "ロード失敗"
loading-failed-desc-decode-error = "ロードに失敗しました。セーブデータが互換のないバージョンで作成されたか、破損しています。"
loading-failed-desc-not-found = "ロードに失敗しました。セーブデータを見つけられません。"

# Events
[event]
start = "新たな惑星\nあなたは不毛な未開の惑星に到着しました。惑星の状態に応じて各種施設を建設し、生命に適した環境に作り変えましょう。\n施設の維持にはエネルギーが、建設には素材が必要です。エネルギーは軌道上に核融合炉を、素材は星系に小惑星採掘ステーションを建設することによって生産できます。\n詳しい情報については適宜ヘルプを参照して下さい。"
