# UI
air-temperature = "気温"
animal = "動物"
argon = "アルゴン"
atmosphere = "大気"
atmosphere-pressure = "気圧"
average-air-temperature = "平均気温"
average-rainfall = "平均降水量"
average-sea-temperature = "平均海水温"
back = "前へ"
biomass = "生物量"
biome = "バイオーム"
build = "建設"
buried-carbon = "埋没炭素"
cancel = "キャンセル"
carbon = "炭素"
carbon-dioxide = "二酸化炭素"
cities = "都市"
city = "都市"
civilization = "文明"
civilize = "文明化"
civilized = "文明化完了"
civilizing-in-progress = "文明化中"
close = "閉じる"
coordinates = "座標"
cost = "コスト"
cycles = "サイクル"
date-saved = "保存日時"
delete = "消去"
demolition = "撤去"
density = "密度"
details = "詳細"
difference-in-elevation = "高低差"
enabled = "有効"
energy = "エネルギー"
energy-consumption = "エネルギー消費量"
exit = "終了"
fertility = "肥沃度"
gene-point = "遺伝子ポイント"
habitability = "居住性"
habitat = "生息環境"
height = "高さ"
help = "ヘルプ"
high = "高"
history = "歴史"
latitude = "緯度"
large = "大型"
layers = "レイヤー"
livable-temperature = "生存可能温度"
load = "ロード"
longitude = "経度"
low = "低"
main-menu = "メインメニュー"
map = "地図"
material = "素材"
medium = "中型"
menu = "メニュー"
messages = "メッセージ"
new = "新規"
new-planet = "新しい惑星"
next = "次へ"
next-tutorial = "次のチュートリアル"
nitrogen = "窒素"
no-civilization = "文明なし"
none = "なし"
ok = "OK"
orbit = "軌道"
oxygen = "酸素"
planet = "惑星"
planet-name = "惑星名"
population = "人口"
preferences = "設定"
produce = "産出"
project = "プロジェクト"
radius = "半径"
rainfall = "降水量"
random-name = "ランダム名"
save = "セーブ"
save-to-slot = "スロット {$slot} にセーブ"
save-to-slot-disabled = "スロットにセーブ        "
search-new-planet = "新しい惑星"
size = "サイズ"
small = "小型"
solar-constant = "太陽定数"
spawn = "配置"
speed-fast = "高速"
speed-normal = "通常速度"
speed-paused = "停止"
star-system = "星系"
start = "開始"
statistics = "統計"
structures = "構造物"
tile-event = "タイルイベント"
tutorial = "チュートリアル"
upkeep = "維持"
water = "水"

# Biomes
land = "陸"
sea = "海"
rock = "岩石"
ocean = "海"
sea-ice = "海氷"
desert = "砂漠"
ice-field = "氷原"
tundra = "ツンドラ"
grassland = "草原"
boreal-forest = "針葉樹林"
temperate-forest = "温帯樹林"
tropical-rainforest = "熱帯雨林"

# Structures
oxygen-generator = "酸素発生機"
rainmaker = "降雨装置"
fertilization-plant = "肥沃化工場"
heater = "ヒーター"
carbon-capturer = "炭素還元機"
gift-tower = "ギフトタワー"
settlement = "居住地"

# Space Buildings
fusion-reactor = "核融合炉"
asteroid-mining-station = "小惑星採掘ステーション"
dyson-swarm-unit = "ダイソンスウォームユニット"
orbital-mirror = "軌道ミラー"
ice-importer = "氷輸送機"
nitrogen-importer = "窒素輸送機"
carbon-importer = "炭素輸送機"
ion-irradiator = "イオン放射機"

# Tile Events
aerosol-injection = "エアロゾル注入"
black-dust = "黒色塵"
fire = "火災"
plague = "疫病"

# Civilization Ages
[age]
stone = "石器"
bronze = "青銅器"
iron = "鉄器"
industrial = "工業化"
atomic = "原子力"
early-space = "初期宇宙"

# Energy sources
[energy_source]
biomass = "バイオマス"
wind-solar = "風力 & 太陽"
hydro-geothermal = "水力 & 地熱"
fossil-fuel = "化石燃料"
nuclear = "原子力"
gift = "ギフト"

# Preferences
[preference]
autosave-enabled = "オートセーブ"
max-simulation-speed = "シミュレーション速度最大化"

# Messages
[msg]
warn-high-temp = "高すぎる気温\n気温が高すぎます。気温を下げるには、軌道上建造物である軌道ミラーを稼働させ、地表に届く太陽光を遮蔽することが効果的です。"
warn-low-oxygen = "酸素が少ない\n大気中に十分な酸素がありません。酸素発生機を設置するか、植物の光合成により酸素を生みだす必要があります。"
warn-low-temp = "低すぎる気温\n気温が低すぎます。気温を上げるには、軌道上建造物である軌道ミラーを稼働させ、地表に届く太陽光を増やすことが効果的です。"
loading-failed = "ロード失敗"
loading-failed-desc-decode-error = "ロードに失敗しました。セーブデータが互換のないバージョンで作成されたか、破損しています。"
loading-failed-desc-not-found = "ロードに失敗しました。セーブデータを見つけられません。"
delete-save-data = "以下のセーブデータを削除しますか?"
save-limit = "ストレージの制限により、Web上で動作している場合は複数のセーブデータを作成できません。"
save-limit-strong = "以下のセーブデータを削除し、新規のゲームをはじめますか? この動作は取り消せません。"

# Events
[event]
start = "新たな惑星\nあなたは不毛な未開の惑星に到着しました。惑星の状態に応じて各種施設を建設し、生命に適した環境に作り変えましょう。\n施設の維持にはエネルギーが、建設には素材が必要です。エネルギーは軌道上に核融合炉を、素材は星系に小惑星採掘ステーションを建設することによって生産できます。\n詳しい情報については適宜ヘルプを参照して下さい。"
