# UI
achivements = "実績"
aggressiveness = "攻撃性"
air-temperature = "気温"
animal = "動物"
animals = "動物"
argon = "アルゴン"
atmosphere = "大気"
atmosphere-pressure = "気圧"
average-air-temperature = "平均気温"
average-rainfall = "平均降水量"
average-sea-temperature = "平均海水温"
back = "前へ"
biomass = "生物量"
biome = "バイオーム"
biomes = "バイオーム"
build = "建設"
building-limit-reached = "建設数限界"
buried-carbon = "埋没炭素"
cancel = "キャンセル"
carbon = "炭素"
carbon-dioxide = "二酸化炭素"
cities = "都市"
city = "都市"
city-icons = "都市アイコン"
civilization = "文明"
civilization-ages = "文明の時代"
civilizations = "文明"
civilize = "文明化"
civilize-cost = "文明化コスト"
civilized = "文明化完了"
civilizing-in-progress = "文明化中"
close = "閉じる"
control = "コントロール"
coordinates = "座標"
cost = "コスト"
credits = "クレジット"
cycles = "サイクル"
date-saved = "保存日時"
delete = "消去"
demolition = "撤去"
density = "密度"
details = "詳細"
difference-in-elevation = "高低差"
enabled = "有効"
energy = "エネルギー"
energy-consumption = "エネルギー消費量"
energy-source-weight = "エネルギー源配分"
energy-sources = "エネルギー源"
exit = "終了"
facilities = "施設"
fertility = "肥沃度"
focus = "注目"
forestation-speed = "植林速度"
gene-points = "遺伝子ポイント"
habitability = "居住性"
habitat = "生息環境"
height = "高さ"
help = "ヘルプ"
high = "高"
history = "歴史"
latitude = "緯度"
large = "大"
layers = "レイヤー"
livable-temperature = "生存可能温度"
load = "ロード"
longitude = "経度"
low = "低"
main-menu = "メインメニュー"
map = "地図"
material = "素材"
medium = "中"
menu = "メニュー"
messages = "メッセージ"
new = "新規"
new-achivement = "実績獲得!"
new-planet = "新しい惑星"
next = "次へ"
next-tutorial = "次のチュートリアル"
nitrogen = "窒素"
no-civilization = "文明なし"
not-enough = "不足"
none = "なし"
ok = "OK"
orbit = "軌道"
oxygen = "酸素"
planet = "惑星"
planet-name = "惑星名"
population = "人口"
population-growth = "人口増加"
power = "電力"
preferences = "設定"
produce = "産出"
project = "プロジェクト"
radius = "半径"
rainfall = "降水量"
random-name = "ランダム名"
reports = "レポート"
resume = "再開"
save = "セーブ"
save-as = "別名でセーブ"
search-new-planet = "新しい惑星"
size = "サイズ"
small = "小"
solar-constant = "太陽定数"
spawn = "配置"
speed-fast = "高速"
speed-medium = "中速"
speed-paused = "停止"
speed-slow = "低速"
star-system = "星系"
start = "開始"
statistics = "統計"
structures = "構造物"
technology-development = "技術開発"
tile-event = "タイルイベント"
tile-events = "タイルイベント"
tutorial = "チュートリアル"
upkeep = "維持"
water = "水"

# Biomes
land = "陸"
sea = "海"
rock = "岩石"
ocean = "海"
sea-ice = "海氷"
desert = "砂漠"
ice-sheet = "氷床"
tundra = "ツンドラ"
grassland = "草原"
boreal-forest = "針葉樹林"
temperate-forest = "温帯樹林"
tropical-rainforest = "熱帯雨林"

# Structures
oxygen-generator = "酸素発生機"
rainmaker = "降雨装置"
fertilization-plant = "肥沃化工場"
heater = "ヒーター"
carbon-capturer = "炭素還元機"
gift-tower = "ギフトタワー"
settlement = "居住地"

# Space Buildings
fusion-reactor = "核融合炉"
asteroid-mining-station = "小惑星採掘ステーション"
dyson-swarm-unit = "ダイソンスウォームユニット"
orbital-mirror = "軌道ミラー"
ice-importer = "氷輸送機"
nitrogen-importer = "窒素輸送機"
carbon-importer = "炭素輸送機"
ion-irradiator = "イオン放射機"

# Tile Events
aerosol-injection = "エアロゾル注入"
black-dust = "黒色塵"
decadence = "退廃"
fire = "火災"
plague = "疫病"
vehicle = "乗り物"
war = "戦争"
nuclear-explosion = "核爆発"
troop = "軍隊"

# Civilization Ages
[age]
stone = "石器"
bronze = "青銅器"
iron = "鉄器"
industrial = "工業化"
atomic = "原子力"
early-space = "初期宇宙"

# Energy sources
[energy_source]
biomass = "バイオマス"
solar-wind = "太陽 & 風力"
hydro-geothermal = "水力 & 地熱"
fossil-fuel = "化石燃料"
nuclear = "原子力"
gift = "ギフト"

# Preferences
[preference]
autosave-enabled = "オートセーブ"
screen-refresh-rate = "画面更新頻度"
show-fps = "FPS表示"
bgm-volume = "BGM音量"
se-volume = "効果音音量"

# Messages
[msg]
animal-insufficient-population = "不十分な個体数"
lack-of-gene-points = "遺伝子ポイント不足"
loading-failed = "ロード失敗"
loading-failed-desc-decode-error = "ロードに失敗しました。セーブデータが互換のないバージョンで作成されたか、破損しています。"
loading-failed-desc-not-found = "ロードに失敗しました。セーブデータを見つけられません。"
delete-save-data = "以下のセーブデータを削除しますか?"
save-limit = "ストレージの制限により、Webブラウザ上で動作している場合は複数のセーブデータを作成できません。"
save-limit-strong = "以下のセーブデータを削除し、新規のゲームをはじめますか? この動作は取り消せません。"
save-limit-file = "消去: {$name}"
save-limit-supplement = "この制限無しにプレイしたい場合はダウンロード版をご使用下さい。"
web-limit-warning = "Gaia MakerはWebブラウザ上で実行されています。Webブラウザ上で実行する場合、セーブデータの数やパフォーマンスが制限されます。制限無しにプレイしたい場合はダウンロード版をご使用下さい。"
control-need-orbital-mirror = "軌道ミラーが建設されていない"
control-need-fertilization-plant = "肥沃化工場が建設されていない"

# Stat items
[stat_item]
planet-name = "惑星の名称"
cycles = "テラフォーミング開始からの経過時間"
radius = "惑星の半径"
population = "文明の人口"
