basics = "基本"
concept = "コンセプト"
player = "プレイヤー"
terraforming = "テラフォーミング"
space-buildings = "建造物"
glossary = "用語"

[help]
concept = "Gaia Maker では、プレイヤーはある未開の惑星とそれを含む星系の管理者となり、テラフォーミングと施設運営を行います。テラフォーミングとは、不毛な惑星を生命が住める環境に改善するプロセスであり、人類が地球以外に大規模な居住地を設けるにはテラフォーミングが不可欠です。各種の施設を建設し、惑星上の大気や気温、植生を調整しましょう。そうすれば、生命にとって理想的な環境を整えることができます。"
player = "管理者であるプレイヤーは、テラフォーミング候補惑星のあるこの星系へと恒星間宇宙船を用いて長い年月をかけやって来ました。管理者は、タイプII文明に相当する技術を持ち、地球型惑星のテラフォーミング技術も所有します。また、母星からテラフォーミングのために様々な動植物の遺伝情報を持ち込んでいます。\n\nタイプII文明とは、カルダシェフ・スケールにおいて、ある星系の全エネルギーを利用できる技術水準を持つ文明を指します。恒星のエネルギーをダイソンスウォームにより集め、その豊富なエネルギーを恒星間航行やテラフォーミングに利用します。"
terraforming = "テラフォーミングの基本は、惑星上の気温、降水量、土壌を調整し、植物を生育することです。そのためには以下の施設が助けになります。\n\n軌道ミラー\n惑星軌道上に建設できるこの施設は、地表に届く恒星の光を増減させ、気温を変化させます。\n\n降雨装置\n海がある惑星であればその周辺に降雨がありますが、そうでなければこの施設で降雨を発生させます。\n\n肥沃化工場\n周辺の肥沃度を増加させ、植物を生育します。"

oxygen-generator = "酸素発生機は、ケイ素といった元素と結合している地殻中の酸素を単離し、大気中に放出します。その過程には十分な電力が必要です。"
rainmaker = "降雨装置は、雨雲を生成し周囲の降雨量を増加させます。"
fertilization-plant = "肥沃化工場は、周辺を植物の育成に適した土壌にゆっくりと変化させます。植物の生育には十分な養分を含む土壌が必要であり、この工場は肥料と土壌改良ドローンを展開することによりその形成を促進します。"
heater = "ヒーターは電力を大気中に熱として放出し、周辺の気温を上昇させます。"
carbon-capturer = "炭素還元機は、大気中の二酸化炭素を収集・還元します。還元により得られた炭素を地中に保存し、酸素は大気中に解放します。"
gift-tower = "ギフトタワーは、周囲の文明にエネルギーを供給します。その文明の技術レベルに応じて、最も利用しやすい形態でのエネルギーを提供します。文明の成長を促進させますが、努力無しに得られるエネルギーは文明に悪影響を与える可能性もあります。"

fusion-reactor = "核融合炉は施設の稼働に必要となる電力を供給します。核融合は宇宙文明にとって不可欠な高効率のエネルギー源ですが、それ以上のエネルギーが必要なのであれば、巨大な核融合炉、恒星の利用が必要でしょう。"
asteroid-mining-station = "小惑星採掘ステーションは、小惑星から鉱石を採掘し、建築などに利用可能な素材に加工します。"
dyson-swarm-unit = "ダイソンスウォームは、恒星の発するエネルギーを余すことなく利用するための巨大建造物であり、ダイソンスフィアの1つの形態です。ユニットひとつひとつは光を反射して需要地まで届ける巨大な鏡に過ぎませんが、数が揃えば惑星改造にも十分なほどのエネルギーを供給します。"
orbital-mirror = "軌道ミラーは、恒星の光を反射し惑星表面に到達する光エネルギーを増減させます。その比率は調整可能です。"
ice-importer = "氷輸送機は、星系内の他の天体から氷を輸送します。惑星にある水の量を増加させます。氷の抽出と輸送には大量の電力が必要です。"
nitrogen-importer = "窒素輸送機はアンモニアを大気として持つ星系内の他の天体から窒素を輸送し、惑星の大気に散布します。窒素の抽出と輸送には大量の電力が必要です。"
carbon-importer = "炭素輸送機は、星系内の他の天体から炭素を輸送し、惑星の大気に二酸化炭素として散布します。炭素の抽出と輸送には大量の電力が必要です。"
ion-irradiator = "イオン放射機は、惑星の大気に加速したイオンを衝突させることにより、その分子を宇宙空間へと弾き飛ばします。大気質量を減らすことにより気圧を下げる効果をもちます。"

aerosol-injection = "惑星の大気圏にエアロゾルを注入します。これにより雲の形成が促進され、多くの場合は恒星からの光を多く反射するようになり気温が低下します。その効果は時間経過とともに減少します。"
black-dust = "地表に黒色の塵を散布します。地表面が恒星の光をより多く吸収し、周囲の気温を上昇させます。この塵は時間経過で消滅します。"
fire = "指定したタイルに火災を起こします。地表のバイオマスを燃やし、文明や動物も焼失させます。二酸化炭素とエアロゾルを増やす効果があります。"
plague = "都市に疫病を広めます。疫病は時間経過で他都市にも感染し、文明の人口を減少させます。"
vehicle = "ある程度発達した文明は船や飛行機で移動します。"
decadence = "ある程度繁栄した文明は、退廃することがあります。退廃した文明では、人々は豊かさの基盤である科学技術、文化、インフラストラクチャーの維持を怠るか、もしくは積極的に破壊するようになります。人口と技術レベルが低下します。"
war = "都市は戦争に巻き込まれることがあります。戦争中の都市は人口が減少します。"
troop = "目標の都市へと進軍する軍隊です。"

rock = "岩石がむき出しの不毛な地域です。生命はほとんど、もしくは全く存在しません。"
ice-sheet = "氷で覆われた地域です。生命は存続できません。恒星の光を効率よく反射するため、周囲をさらに冷やす効果があります。"
desert = "乾燥により植物が育たない不毛な地域です。たとえ生命が存在してもその量はわずかです。"
ocean = "ある程度の面積と深さのある水域です。惑星にとっての重要な水源であり、海洋生物が生息できます。"
sea-ice = "低温のため海面が凍った海域です。"
grassland = "草地の広がる肥沃な地域です。森林が発達するほどの降雨がない場合、草原になります。森林に比べると生物は少ないです。"
tundra = "地下に永久凍土の存在する地域です。寒冷なため森林は発達しませんが、ある程度の生命が存在します。"
boreal-forest = "気温の低い地域に形成される森林です。"
temperate-forest = "温暖な地域に形成される森林です。多くの生命が存在します。"
tropical-rainforest = "温帯樹林よりさらに温暖で湿潤な地域に形成される森林です。多くの生命が存在します。"

oxygen = "生命が存在するためには酸素が不可欠です。大気に20%含まれる状態が理想的で、少なすぎても多すぎても問題になります。"
nitrogen = "窒素は大気圧を保つために不可欠です。また生命の重要な構成元素の1つでもあり、大気中の窒素の一部は生命に取り込まれます。"
carbon-dioxide = "植物が生長するためには二酸化炭素が不可欠です。またその温室効果により、惑星の気温を調整する役割を果たします。少なすぎると寒冷化の原因に、多すぎると温暖化の原因になります。そのため、その濃度変化は惑星全体の環境に大きな影響を与えます。"
argon = "アルゴンは化学反応をほとんど起こさないため、その濃度はほとんど変化しません。惑星の大気圧を保つのにわずかながら寄与します。"

biomass = "その土地、もしくは惑星全体において存在する生物の量を炭素の質量で表します。植物が育つと大気中の二酸化炭素が生命の中に炭素として蓄えられます。逆に、火災などで土地のバイオマスが減少すると、大気に二酸化炭素として放出されます。バイオマスが多い土地であるほど動物は繁殖しやすくなります。"
civilization = "ある程度の知能を持ち、道具を使用するのに適した体格を持つ動物は、遺伝子操作によって知性化を行い、文明をもたせることができます。彼らは惑星から外に出ることができない、プレイヤーから見れば原始的な文明を築きます。文明は石器時代の技術からスタートし、時間経過によってより高度な技術を獲得していきます。拡大した文明の存在は、惑星の環境にも影響を及ぼします。"
cloud-albedo = "雲によって反射される恒星の光の割合を表します。"
fertility = "陸上であれば土壌の肥沃さ、海であれば海水の栄養量を表します。肥沃な土地であれば森林が育ち、また文明が繁栄しやすくなります。土地が肥沃になるためには適切な気温と降水が必要です。"
solar-constant = "惑星が恒星から受け取るエネルギーを表します。これが大きいほど惑星の気温が高くなります。建造物や自然現象によって増減します。"

[help.age]
stone = "原始的な道具として石器を用い、原始的な農業を始めた文明です。人口は少なくエネルギー消費も少ないので生態系への影響は少ないですが、わずかながらエネルギー源としてバイオマスを消費します。"
bronze = "石器より洗練された道具を用い、初歩的な金属加工の技術を持つ文明です。都市への定住や社会の形成が行われています。また、文字の発明により技術や文化を後世に伝えるようになりました。主なエネルギー源はバイオマスです。"
iron = "鉄を道具の製作に使用し、集約的な農業を行い複雑な社会を形成している文明です。鉄の製造には大きなエネルギーを消費し、その源はバイオマスであるため、森林破壊などの生態系への悪影響をもたらします。僅かながら水力や風力、化石燃料をエネルギー源として使用します。"
industrial = "工場による製品の大量生産を行うようになった文明です。人口とエネルギー消費は飛躍的に増大します。化石燃料かそれ以上に高効率なエネルギーが無ければ社会の維持は不可能です。主なエネルギー源は化石燃料と水力です。"
atomic = "核分裂エネルギーを利用する技術を持つ文明です。化石燃料も可能であれば利用します。高効率なエネルギーから発展した社会を築いていますが、核戦争が起こる可能性があります。"
early-space = "核融合エネルギーを利用する技術を持つ文明です。これは、もはや自然界の資源を収奪することなく文明を存続させるほどのエネルギーを得られていることを意味します。また、その余剰エネルギーは、惑星の重力から脱出するのに十分なほどです。"

[help.energy_source]
biomass = "薪や動物の油などを燃焼させたり、家畜を労働させて得るエネルギーです。文明の技術レベルに関係なく利用することができますが、自然界のバイオマスを直接消費するため、文明の消費エネルギーが多い場合にこれに頼ると著しい環境破壊をもたらします。技術が進歩し、他のエネルギーが利用可能になると、消費量は減少していきます。"
solar-wind = "恒星からの光や風をエネルギー源とします。エネルギーの密度が希薄であるという特性があるため、大量のエネルギーを得るには広い面積が必要であり、土地の確保で環境破壊をもたらします。またその不安定さから、このエネルギー源の割合が増えるほど効率が減少します。しかしながら、技術の進歩した文明の場合、補助的に使用するのであれば高効率のエネルギー源になりえます。"
hydro-geothermal = "川の流れや地熱からエネルギーを取り出します。工業化した文明にとって高効率なエネルギー源として重要です。しかし利用可能な量は限られます。わずかながら環境破壊をもたらします。"
fossil-fuel = "地中に埋まった炭素を燃焼させエネルギーを取り出します。工業化した文明にとって重要なエネルギー源です。利用するには、その文明が炭素の埋まっている土地を確保している必要があり、惑星によっては利用不可能なこともあります。また文明が化石燃料を消費すると二酸化炭素が排出されます。採掘や消費においてわずかながら環境破壊をもたらします。"
nuclear = "ウランやトリウムなどから得られる核分裂エネルギーや、重水素による核融合エネルギーです。惑星上で知的生命体が手にし得る最も高効率なエネルギー源で、環境への負荷もほとんどありません。物理学的には理想的なエネルギー源ですが、利用には高い技術レベルを維持する必要があります。また、原子力エネルギーを利用可能な文明は、核戦争ができる技術も有していることは覚えておくべきでしょう。"
gift = "管理者がもつエネルギーを、地上の原始文明が利用できるようにしたものです。その文明の技術レベルに応じて、最も利用しやすい形態で供給されます。本来なら原始文明が手にすることができないような高効率のエネルギーですが、それゆえ文明の進化に大きな影響を与えるでしょう。"
