basics = "基本"
concept = "コンセプト"
player = "プレイヤー"
terraforming = "テラフォーミング"
space-buildings = "建造物"

[help]
concept = "Gaia Maker では、プレイヤーはある未開の惑星とそれを含む星系の管理者となり、テラフォーミングと施設運営を行います。テラフォーミングとは、不毛な惑星を生命が住める環境に改善するプロセスであり、人類が地球以外に大規模な居住地を設けるにはテラフォーミングが不可欠です。各種の施設を建設し、惑星上の大気や気温、植生を調整しましょう。そうすれば、生命にとって理想的な環境を整えることができます。"
player = "管理者であるプレイヤーは、テラフォーミング候補惑星のあるこの星系へと恒星間宇宙船を用いて長い年月をかけやって来ました。管理者は、タイプII文明に相当する技術を持ち、地球型惑星のテラフォーミング技術も所有します。また、母星からテラフォーミングのために様々な動植物の遺伝情報を持ち込んでいます。\n\nタイプII文明とは、カルダシェフ・スケールにおいて、ある星系の全エネルギーを利用できる技術水準を持つ文明を指します。恒星のエネルギーをダイソンスウォームにより集め、その豊富なエネルギーを恒星間航行やテラフォーミングに利用します。"
terraforming = "テラフォーミングの基本は、惑星上の気温、降水量、土壌を調整し、植物を生育することです。そのためには以下の施設が助けになります。\n\n軌道ミラー\n惑星軌道上に建設できるこの施設は、地表に届く恒星の光を増減させ、気温を変化させます。\n\n降雨装置\n海がある惑星であればその周辺に降雨がありますが、そうでなければこの施設で降雨を発生させます。\n\n肥沃化工場\n周辺の肥沃度を増加させ、植物を生育します。"

oxygen-generator = "酸素発生機は、ケイ素といった元素と結合している地殻中の酸素を単離し、大気中に放出します。その過程には十分なエネルギーが必要です。"
rainmaker = "降雨装置は、雨雲を生成し周囲の降雨量を増加させます。"
fertilization-plant = "肥沃化工場は、周辺を植物の育成に適した土壌にゆっくりと変化させます。植物の生育には十分な養分を含む土壌が必要であり、この工場は肥料と土壌改良ドローンを展開することによりその形成を促進します。"
heater = "ヒーターはエネルギーを大気中に熱として放出し、周辺の気温を上昇させます。"
carbon-capturer = "炭素還元機は、大気中の二酸化炭素を収集・還元します。還元により得られた炭素を地中に保存し、酸素は大気中に解放します。"
gift-tower = "ギフトタワーは、周囲の文明にエネルギーを供給します。その文明の技術レベルに応じて、最も利用しやすい形態でのエネルギーを提供します。文明の成長を促進させますが、努力無しに得られるエネルギーは文明に悪影響を与える可能性もあります。"

fusion-reactor = "核融合炉は施設の稼働に必要となるエネルギーを供給します。核融合は宇宙文明にとって不可欠な高効率のエネルギー源ですが、それ以上のエネルギーが必要なのであれば、巨大な核融合炉、恒星の利用が必要でしょう。"
asteroid-mining-station = "小惑星採掘ステーションは、小惑星から鉱石を採掘し、建築などに利用可能な素材に加工します。"
dyson-swarm-unit = "ダイソンスウォームは、恒星の発するエネルギーを余すことなく利用するための巨大建造物であり、ダイソンスフィアの1つの形態です。ユニットひとつひとつは光を反射して需要地まで届ける巨大な鏡に過ぎませんが、数が揃えば惑星改造にも十分なほどのエネルギーを供給します。"
orbital-mirror = "軌道ミラーは、恒星の光を反射し惑星表面に到達する光エネルギーを増減させます。その比率は調整可能です。"
ice-importer = "氷輸送機は、星系内の他の天体から氷を輸送します。惑星にある水の量を増加させます。氷の抽出と輸送には大量のエネルギーが必要です。"
nitrogen-importer = "窒素輸送機はアンモニアを大気として持つ星系内の他の天体から窒素を輸送し、惑星の大気に散布します。窒素の抽出と輸送には大量のエネルギーが必要です。"
carbon-importer = "炭素輸送機は、星系内の他の天体から炭素を輸送し、惑星の大気に二酸化炭素として散布します。炭素の抽出と輸送には大量のエネルギーが必要です。"
ion-irradiator = "イオン放射機は、惑星の大気に加速したイオンを衝突させることにより、その分子を宇宙空間へと弾き飛ばします。大気質量を減らすことにより気圧を下げる効果をもちます。"

aerosol-injection = "惑星の大気圏にエアロゾルを注入します。これにより雲の形成が促進され、多くの場合は恒星からの光を多く反射するようになり気温が低下します。その効果は時間経過とともに減少します。"
black-dust = "地表に黒色の塵を散布します。地表面が恒星の光をより多く吸収し、周囲の気温を上昇させます。この塵は時間経過で消滅します。"
fire = "指定したタイルに火災を起こします。地表のバイオマスを燃やし、文明や動物も焼失させます。二酸化炭素とエアロゾルを増やす効果があります。"
plague = "都市に疫病を広めます。疫病は時間経過で他都市にも感染し、文明の人口を減少させます。"
vehicle = "ある程度発達した文明は船や飛行機で移動します。"
war = "都市は戦争に巻き込まれることがあります。戦争中の都市は人口が減少します。"
