[report]
warn-high-temp = "気温が高すぎます。気温を下げるには、軌道上建造物である軌道ミラーを稼働させ、地表に届く太陽光を遮蔽することが効果的です。"
warn-low-carbon-dioxide = "大気中に十分な二酸化炭素がありません。植物の生長が阻害され、寒冷化をもたらす場合もあります。炭素輸送機を稼働させるか、埋没炭素を燃焼させる必要があります。"
warn-low-oxygen = "大気中に十分な酸素がありません。酸素発生機や炭素還元機を設置しましょう。"
warn-low-temp = "気温が低すぎます。気温を上げるには、軌道上建造物である軌道ミラーを稼働させ、地表に届く太陽光を増やすことが効果的です。"
animal-born = "{$animal}が誕生しました"
achive-civilization = "{$animal}が文明を獲得しました"
civilized = "{$animal}の文明化が完了しました"
civ-advance = "{$civ} が {$age}時代 に進歩しました"
civ-extinct = "{$civ} が滅亡しました"
civ-decadence = "{$civ} の退廃が始まりました"
inter-species-war = "{$civ_a}と{$civ_b}が戦争状態に入りました"
inter-species-war-ceased = "{$civ_a}と{$civ_b}の戦争が終結しました"
nuclear-war = "核戦争が始まった"
