[tutorial]
start-0 = "あなたは長い旅路の末、テラフォーミングに適した惑星へ到着しました。この惑星の管理者となり、テラフォーミングにより生命に適した環境へと作り変えましょう。"
start-1-1 = "惑星上で視点を移動するには、WASDもしくは方向キーを使います。"
start-1-2 = "惑星の全体を把握したい場合は、ツールバーから以下のアイコンをクリックしてマップを表示します。"
power-0-1 = "テラフォーミングに用いる施設を稼働させるには、十分な電力が必要です。現在どれだけの電力が消費・生産されているかは、サイドバーで以下のように示されています。"
power-0-2 = "施設の建設には素材が必要です。現在どれだけの素材が貯蔵・生産されているかは、サイドバーで以下のように示されています。"
power-1-1 = "電力や素材の生産量を増やすには、ツールバーの以下のアイコンをクリックして建造物ウィンドウを開き、核融合炉と小惑星採掘ステーションを建設します。"
power-1-2 = "「+1」と書かれたボタンをクリックして、指定された数だけ建物を建造しましょう。"
power-checklist1 = "核融合炉を5つ以上保有する"
power-checklist2 = "小惑星採掘ステーションを5つ以上保有する"
