[tutorial]
start-0 = "あなたは長い旅路の末、テラフォーミングに適した惑星へ到着しました。この惑星の管理者となり、テラフォーミングにより生命に適した環境へと作り変えましょう。"
start-1-1 = "惑星上で視点を移動するには、WASDもしくは方向キーを使います。"
start-1-2 = "惑星の全体を把握したい場合は、ツールバーから以下のアイコンをクリックしてマップを表示します。"
