[tutorial]
start-0 = "あなたは長い旅路の末、テラフォーミングに適した惑星へ到着しました。この惑星の管理者となり、テラフォーミングにより生命に適した環境へと作り変えましょう。"
start-1-1 = "惑星上で視点を移動するには、WASDもしくは方向キーを使います。"
start-1-2 = "惑星の全体を把握したい場合は、ツールバーから以下のアイコンをクリックしてマップを表示します。"

power-0-1 = "テラフォーミングに用いる施設を稼働させるには、十分な電力が必要です。現在どれだけの電力が消費・生産されているかは、サイドバーで以下のように示されています。"
power-0-2 = "施設の建設には素材が必要です。現在どれだけの素材が貯蔵・生産されているかは、サイドバーで以下のように示されています。"
power-1-1 = "電力や素材の生産量を増やすには、ツールバーの以下のアイコンをクリックして建造物ウィンドウを開き、核融合炉と小惑星採掘ステーションを建設します。"
power-1-2 = "「+1」と書かれたボタンをクリックして、指定された数だけ建物を建造しましょう。"
power-checklist1 = "核融合炉を5つ以上保有する"
power-checklist2 = "小惑星採掘ステーションを5つ以上保有する"

fertilize-0-1 = "ある程度の電力が確保できたら、惑星の緑化を始めましょう。\n植物が育つためには、陸上で、さらにほどよい気温と降水という条件が必要です。カーソル下のタイルの気温と降水量をサイドバーで確認できるので、それで植物に適したタイルを探して下さい。気温と降水量は以下のアイコンで表されています。"
fertilize-0-2 = "気温の目安は10〜30°C、降水量の目安は500mm以上です。"
fertilize-1-1 = "良い条件のタイルを見つけたら、ツールバーの以下のアイコンをクリックしてメニューを開き、肥沃化工場を選択します。そして、目的のタイルをクリックして建設して下さい。"
fertilize-1-2 = "肥沃化工場は距離を離していくつか建設しましょう。建設し終わったら、ツールバーの以下のアイコンをクリックして時間を進めましょう。"
fertilize-checklist1 = "肥沃化工場を3つ以上建設する"
fertilize-checklist2 = "草原が10タイル以上に広がる"

build-oxygen-0-1 = "おめでとうございます。惑星に生命が根付き始めました。次は、大気の状態を確認しましょう。ツールバーの以下のアイコンをクリックして統計ウィンドウを開き、大気のタブをクリックしましょう。"
build-oxygen-0-2 = "森林や動物といった高度な生態系が形成されるには、惑星の大気にある程度の酸素が必要です。酸素が少ない場合は、酸素発生機を建設しましょう。"
build-oxygen-1-1 = "酸素発生機の稼働には、潤沢な電力が必要です。ツールバーの以下のアイコンをクリックして建造物ウィンドウを開き、ダイソンスウォームユニットを建設して電力を確保します。"
build-oxygen-1-2 = "建設に必要な素材が足りない場合は、小惑星採掘ステーションを建設して時間を進めて下さい。\n電力を確保したら、ツールバーの以下のアイコンをクリックしてメニューを開き、酸素発生機を選択します。そして、空いているタイルをクリックして建設して下さい。"
build-oxygen-checklist1 = "ダイソンスウォームユニットを5つ以上保有する"
build-oxygen-checklist2 = "酸素発生機を8つ以上建設する"

wait-oxygen-0-1 = "酸素発生機を建設したら、酸素濃度が上がり、森林が形成されるまで待ちましょう。\nこの過程は時間がかかるので、ツールバーの以下のアイコンをクリックして速く時間を進めましょう。"
wait-oxygen-0-2 = "この過程を早く終わらせたい場合、素材が貯まり次第、ダイソンスウォームユニットと酸素発生機を追加しましょう。"
wait-oxygen-checklist1 = "酸素の分圧が0.12 atmに達する"
wait-oxygen-checklist2 = "森林が50タイル以上に広がる"
