[tutorial]
start-0 = "あなたは長い旅路の末、テラフォーミングに適した惑星へ到着しました。この惑星の管理者となり、テラフォーミングにより生命に適した環境へと作り変えましょう。"
start-1-1 = "惑星上で視点を移動するには、WASDもしくは方向キーを使います。"
start-1-2 = "マウスのミドルクリックでカーソルのあるタイルに視点を移動し、ホイールでズームイン・ズームアウトができます。"
start-1-3 = "また、画面右下のマップでは、惑星全体の状態を把握できます。マップを閉じている場合は画面右下の以下のアイコンをクリックして下さい。"

power-0-1 = "テラフォーミングに用いる施設を稼働させるには、十分な電力が必要です。現在どれだけの電力が消費・生産されているかは、画面上部に以下のように示されています。"
power-0-2 = "施設の建設には素材が必要です。現在どれだけの素材が貯蔵・生産されているかは、画面上部で以下のように示されています。"
power-1-1 = "電力や素材の生産量を増やすには、画面左上にある以下のアイコンをクリックして建造物ウィンドウを開き、核融合炉と小惑星採掘ステーションを建設します。"
power-1-2 = "「+1」と書かれたボタンをクリックして、指定された数だけ建物を建造しましょう。"
power-checklist1 = "核融合炉を5つ以上保有する"
power-checklist2 = "小惑星採掘ステーションを5つ以上保有する"

fertilize-0-1 = "ある程度の電力が確保できたら、惑星の緑化を始めましょう。\n植物が育つためには、陸上で、さらにほどよい気温と降水という条件が必要です。カーソル下のタイルの気温と降水量を画面右上のインジケーターで確認できるので、それで植物に適したタイルを探して下さい。気温と降水量は以下のアイコンで表されています。"
fertilize-0-2 = "気温の目安は10〜30°C、降水量の目安は500mm以上です。"
fertilize-1-1 = "良い条件のタイルを見つけたら、画面上部のツールバーの以下のアイコンをクリックしてメニューを開き、肥沃化工場を選択します。そして、目的のタイルをクリックして建設して下さい。"
fertilize-1-2 = "肥沃化工場は距離を離していくつか建設しましょう。建設し終わったら、ツールバーの以下のアイコンをクリックして時間を進めましょう。"
fertilize-1-3 = "時間が経つと、以下の例のように草原が広がっていきます。いつまで経っても草原が生成されない場合、気温と降水量を再度確認しましょう。"
fertilize-checklist1 = "地上に肥沃化工場を3つ以上建設する"
fertilize-checklist2 = "草原が10タイル以上に広がる"

build-oxygen-0-1 = "おめでとうございます。惑星に生命が根付き始めました。次は、大気の状態を確認しましょう。画面左下にある以下のアイコンをクリックして統計ウィンドウを開き、「大気」のタブをクリックしましょう。"
build-oxygen-0-2 = "森林や動物といった高度な生態系が形成されるには、惑星の大気にある程度の酸素が必要です。酸素が少ない場合は、酸素発生機を建設しましょう。"
build-oxygen-1-1 = "酸素発生機の稼働には、潤沢な電力が必要です。画面左上にある以下のアイコンをクリックして建造物ウィンドウを開き、ダイソンスウォームユニットを建設して電力を確保します。"
build-oxygen-1-2 = "建設に必要な素材が足りない場合は、小惑星採掘ステーションを建設して時間を進めて下さい。\n電力を確保したら、ツールバーの以下のアイコンをクリックしてメニューを開き、酸素発生機を選択します。そして、空いているタイルをクリックして建設して下さい。"
build-oxygen-checklist1 = "ダイソンスウォームユニットを5つ以上保有する"
build-oxygen-checklist2 = "地上に酸素発生機を8つ以上建設する"

wait-oxygen-0-1 = "酸素発生機を建設したら、酸素濃度が上がり、森林が形成されるまで待ちましょう。肥沃度の高いタイルは、植物が成長するにつれバイオマスが増え、やがて森林へと変化します。\nこの過程は時間がかかるので、ツールバーの以下のアイコンをクリックして速く時間を進めましょう。"
wait-oxygen-0-2 = "この過程を早く終わらせたい場合、素材が貯まり次第、ダイソンスウォームユニットと酸素発生機を追加しましょう。"
wait-oxygen-checklist1 = "酸素の分圧が0.12 atmに達する"
wait-oxygen-checklist2 = "森林が50タイル以上に広がる"

carbon-0-1 = "この惑星の大気は、少し二酸化炭素が多いようです。二酸化炭素はやがて植物が吸収してくれますが、炭素還元機を使えばより速く二酸化炭素を取り除くことができます。取り除かれた炭素は地下に埋没炭素として蓄えられ、後の時代に文明が化石燃料として利用します。\nツールバーの以下のアイコンをクリックしてメニューを開き、炭素還元機を選択します。そして、空いているタイルをクリックして建設して下さい。"
carbon-0-2 = "建設する電力が足りない場合は、ダイソンスウォームユニットを追加するか、酸素発生機を撤去します。撤去は建設と同じメニューから選択できます。"
carbon-checklist1 = "地上に炭素還元機を2つ以上建設する"

animal-0-1 = "もし現状、十分な森林が形成されているなら、好みの動物を繁殖させるために必要な条件は整っていると言えるでしょう。動物の配置には遺伝子ポイントが必要です。現在どれだけの遺伝子ポイントが貯められているかは、画面上部に以下で以下のように示されています。"
animal-0-2 = "遺伝子ポイントは時間経過で少しずつ増加します。その増加量は惑星上の生物が増えると大きくなります。"
animal-1-1 = "動物を配置するには、画面左上にある以下のアイコンをクリックして動物ウィンドウを表示します。"
animal-1-2 = "動物のリストから好みの動物を選択し、配置ボタンを押してからタイルをクリックすることで動物を配置することができます。\n動物を配置するとき、配置するタイルはその動物に適した環境である必要があります。ヒトデの場合は海洋です。適した環境に配置すれば、時間経過で周りのタイルにも繁殖していきます。また、別の種の動物に変異することもあります。"
animal-checklist1 = "動物が30タイル以上に居住"

civilize-0-1 = "動物はやがて進化し文明をもちますが、文明化のプロセスにより意図手的に文明をもたせることもできます。画面上部のツールバーの以下のアイコンをクリックしてメニューを開き、文明化を選択します。"
civilize-0-2 = "そして動物のいるタイルをクリックすると、文明化された動物の都市が出現します。"
civilize-checklist1 = "惑星上に文明の都市が存在する"

control-civ-0-1 = "惑星上の文明に干渉し、その方向性を変化させることが可能です。画面左上にある以下のアイコンをクリックしてコントロールウィンドウを表示し、「文明」のタブをクリックします。"
control-civ-0-2 = "試しに、人口増加のスライダーを150%以上に調節してみましょう。これで文明の人口がより増えやすくなります。\n戦争の頻度やエネルギー源も調節できます。"
control-civ-checklist1 = "文明の人口増加を150%以上に調節する"

orbital-mirror-0-1 = "惑星上の生命や文明のために、その気温を即座に細かく調整する場合、軌道ミラーが最も適した方法です。画面左上にある以下のアイコンをクリックして建造物ウィンドウを開き、軌道ミラーの項目で「+1」と書かれたボタンをクリックし建設しましょう。"
orbital-mirror-0-2 = "軌道ミラーは、恒星からの光を直接調節する建造物です。軌道ミラーの項目にあるスライドバーから調節できます。\n光量の変化はわずかな割合でも惑星に多大な影響をあたえるので、まずは-10〜-5%の範囲に動かして、少し温度を下げてみましょう。\nそして惑星全体の平均温度や生物量がどう変化したかは、統計ウィンドウにある「歴史」のタブからグラフで確認できます。統計ウィンドウは画面左下の以下のアイコンをクリックすると開けます。"
orbital-mirror-checklist1 = "軌道ミラーを保有する"
orbital-mirror-checklist2 = "軌道ミラーを-10〜-5%の範囲に調節する"

complete-0-1 = "おめでとうございます。文明が発展できるほど惑星の環境を整えることができました。このまま惑星の環境をさらに改善するのも、動物や文明を見守るのも、または滅ぼしてしまうのもあなたの自由です。\nチュートリアルはこれで終わりですが、このまま続けてもできます。他の惑星から開始する場合は、メインメニューから「新規」を選ぶことができます。"
